<?php

namespace ABO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository{
    
    /*
     * Trademark:Admin:navigation
     */
    public function getSubCategories($categories) {
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
            ->from('ABOMainBundle:Category', 'c')
            ->join('c.parent', 'p')
            ->addSelect('p')
            ->add('where', $qb->expr()->in('p.id', $categories));
        
        return $qb->getQuery()->getResult();
    }
    
    /*
     * SetCategories methods (Trademark,Shop,User)
     */
    public function getCategoriesForSettings() {
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
            ->from('ABOMainBundle:Category', 'c')
            ->join('c.parent', 'p')
            ->addSelect('p')
            ->where('c.level = :level')
            ->setParameter('level', 2);
        
        return $qb->getQuery()->getResult();
    }
    
    /*
     * CategoryType query_builder
     */
    public function getCategoryChildren($slug) {
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
            ->from('ABOMainBundle:Category', 'c')
            ->join('c.parent', 'p')
            ->addSelect('p')
            ->where('p.slug = :slug')
            ->setParameter('slug', $slug);
        
        return $qb; //->getQuery()->getResult()
    }

    /*
     * ABOCategory service
     */
    public function getCatsByParent(Category $parent) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
            ->from('ABOMainBundle:Category', 'c')
            ->where('c.parent = :parent')
            ->setParameter('parent', $parent);

        return $qb->getQuery()->getResult();
    }
    
}
