<?php

namespace ABO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryUserRepository extends EntityRepository{
    
    /*
     * User:Profile:show
     */
    public function userCategoriesNb($user) {
        $qb = $this->createQueryBuilder('uc')
            ->addSelect('uc')
            ->select('COUNT(uc)')
            ->where('uc.user = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    /*
     * User:Profile:setCategories
     */
    public function userCategories($user) {
        $qb = $this->createQueryBuilder('uc')
            ->addSelect('uc')
            ->join('uc.category', 'c')
            ->addSelect('c')
            ->orWhere('uc.chosen = :chosen')
            ->orWhere('uc.productNb > :productNb')
            ->andWhere('uc.user = :user')
            ->setParameters(array('user'=>$user,'chosen'=>true,'productNb'=>0));

        return $qb->getQuery()->getResult();
    }
}
