<?php

namespace ABO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EmailShopRepository extends EntityRepository {
    
    public function getEmails($shop) {
        
        $qb = $this->createQueryBuilder('es')
            ->addSelect('es')
            ->where('es.shop = :shop')
            ->setParameter('shop', $shop)
            ->setMaxResults(3);

        return $qb->getQuery()->getResult();
    }
}
