<?php

namespace ABO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class FeatureRepository extends EntityRepository {
    
    public function getEmails($shop) {
        
        $qb = $this->createQueryBuilder('es')
            ->addSelect('es')
            ->where('es.shop = :shop')
            ->setParameter('shop', $shop)
            ->setMaxResults(3);

        return $qb->getQuery()->getResult();
    }
    public function findAllByLocale($id, $locale = 'en') {
        
        //Make a Select query
        $qb = $this->createQueryBuilder('f')
            ->select('f')
            ->where('f.id = :id')
            ->setParameter('id', $id);
        
        $query = $qb->getQuery();
        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        
        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            $locale
        );
        return $query->getOneOrNullResult();
    }
}
