<?php

namespace ABO\MainBundle\Entity;

/**
 * GenSpecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralSpecRepository extends \Doctrine\ORM\EntityRepository
{
}
