<?php

namespace ABO\MainBundle\Entity;

use ABO\ShopBundle\Entity\Shop;
use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageShopRepository extends EntityRepository{
    
    /*
     * Main:Modal:shopImageForm
     */
    public function getImagesByType(Shop $shop, $type) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('ims')
            ->from('ABOMainBundle:ImageShop', 'ims')
            ->join('ims.image', 'i')
            ->addSelect('i')
            ->where('i.type = :type')
            ->andWhere('ims.shop = :shop')
            ->setParameters(array('type'=>$type, 'shop'=>$shop));
        return $qb->getQuery()->getResult();
    }
}
