<?php

namespace ABO\MainBundle\Entity;

use ABO\ShopBundle\Entity\Shop;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageUserRepository extends EntityRepository{
    
    /*
     * Main:Modal:userImageForm
     */
    public function getImages(UserInterface $user) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('iu')
            ->from('ABOMainBundle:ImageUser', 'iu')
            ->join('iu.image', 'i')
            ->addSelect('i')
            ->andWhere('iu.user = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }
}
