<?php

namespace ABO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class PhoneUserRepository extends EntityRepository {
    
    public function getPhones($user) {
        
        $qb = $this->createQueryBuilder('pu')
            ->addSelect('pu')
            ->where('pu.user = :user')
            ->setParameter('user', $user)
            ->setMaxResults(3);

        return $qb->getQuery()->getResult();
    }
}
