<?php

namespace ABO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductColorRepository extends EntityRepository {

    /*
     * Trademark:Product:addModel
     */
    public function getParentColors($catProd){
        $qb = $this->createQueryBuilder('pc')
            ->addSelect('pc')
            ->join('pc.color', 'c')
            ->addSelect('c')
            ->where('pc.categoryProduct = :catProd')
            ->setParameter('catProd', $catProd);

        return $qb->getQuery()
            ->getResult();
    }
}
