security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_TAJER:    ROLE_USER
        ROLE_ADMIN:    ROLE_USER
        ROLE_SUPER_ADMIN:    ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: abo_user_security_login
                check_path: abo_user_security_check
                default_target_path: abo_user_profile_show
            remember_me:
                secret: '%secret%'
                lifetime: 1296000 # 15 days | 31536000 365 days in seconds
                path: abo_main_home_home
            oauth:
                resource_owners:
                    facebook:      facebook_login
                    google:        google_login
                login_path:        abo_user_security_login
                failure_path:      abo_user_security_login
 
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:
                path: abo_user_security_logout
                target: abo_main_gallery_gallery
                invalidate_session: true
                delete_cookies:
                    SIABOMATEJER: { path: null, domain: null }

            anonymous:    true

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
