<?php

namespace ABO\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getFullUser($user_id){

        $qb = $this->createQueryBuilder('u')
        ->addSelect('u')
        ->join('u.address', 'a')
        ->addSelect('a')
        ->leftJoin('u.image', 'i')
        ->addSelect('i')
        ->leftJoin('u.myShop', 's')
        ->addSelect('s')
        ->where('u.id = :id')
        ->setParameter('id', $user_id);
        
        return $qb->getQuery()->getOneOrNullResult();
        
    }
    
    public function getUserWithShop($user_id){

        $qb = $this->createQueryBuilder('u')
        ->addSelect('u')
        ->join('u.image', 'i')
        ->addSelect('i')
        ->join('u.myShop', 's')
        ->addSelect('s')
        ->join('s.rateStat', 'r')
        ->addSelect('r')
        ->join('s.image', 'im')
        ->addSelect('im')
        ->where('u.id = :id')
        ->setParameter('id', $user_id);
        
        return $qb->getQuery()->getOneOrNullResult();
    }
    
}
