<?php

namespace ABO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryShopRepository extends EntityRepository{
    
    /*
     * User:Shop:subscribed
     * User:Shop:shopByCategory
     * Shop:Show:navigation
     * Shop:Admin:collections
     * Shop:admin:setCategories
     * Main:Modal:ShopInfo
     */
    public function getCategories($shop){
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('cs')
            ->from('ABOShopBundle:CategoryShop', 'cs')
            ->join('cs.category', 'c')
            ->addSelect('c')
            ->where('cs.shop = :shop')
            ->setParameter('shop', $shop);
        return $qb->getQuery()
            ->getResult();
    }
    
    /*
     * User:Show:homeAdmin
     */
    public function shopCategoriesNb($shop) {
        $qb = $this->createQueryBuilder('cs')
            ->addSelect('cs')
            ->select('COUNT(cs)')
            ->where('cs.shop = :shop')
            ->setParameter('shop', $shop);

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function getShops($category) {
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('cs')
            ->from('ABOShopBundle:CategoryShop', 'cs')
            ->join('cs.shop', 's')
            ->addSelect('s')
            ->where('cs.category = :category')
            ->setParameter('category', $category);
        return $qb->getQuery()
            ->getResult();
    }
}
