<?php

namespace ABO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionProductRepository extends EntityRepository{
    
    /*
     * shop:OfferType
     */
    public function getCollectionPS($collection){
        
        $parameters = array('collection' => $collection);
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('cop')
            ->from('ABOShopBundle:CollectionProduct', 'cop')
            ->join('cop.productShop', 'ps')
            ->addSelect('ps')
            ->join('ps.categoryProduct', 'cp')
            ->addSelect('cp')
            ->join('cp.product', 'p')
            ->addSelect('p')
            ->join('cp.category', 'c')
            ->addSelect('c')
            ->join('cp.image', 'i')
            ->addSelect('i')
            ->join('cp.rateStat', 'r')
            ->addSelect('r')
            ->join('cp.generalSpecs', 'g')
            ->addSelect('g')
            ->leftJoin('cp.shop', 's')
            ->addSelect('s')
            ->leftJoin('s.image', 'si')
            ->addSelect('si')
            ->leftJoin('cp.trademark', 't')
            ->addSelect('t')
            ->leftJoin('t.image', 'ti')
            ->addSelect('ti')
            ->where('cop.collection = :collection')
            ->setParameters($parameters);
        
        return $qb->getQuery();
    }
    
    /*
     * Main:Modal:Offer
     */
    public function getOfferCollections($productShop){
        
        $parameters = array('productShop' => $productShop);
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('cp')
            ->from('ABOShopBundle:CollectionProduct', 'cp')
            ->join('cp.collection', 'c')
            ->addSelect('c')
            ->where('cp.productShop = :productShop')
            ->setParameters($parameters);
        
        return $qb->getQuery()->getResult();
    }
}
