<?php

namespace ABO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentProductRepository extends EntityRepository{
    
    /*
     * Main:Modal:Offer
     */
    public function getOfferPayments($productShop){
        
        $parameters = array('productShop' => $productShop);
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('pp')
            ->from('ABOShopBundle:PaymentProduct', 'pp')
            ->join('pp.payment', 'p')
            ->addSelect('p')
            ->where('pp.productShop = :productShop')
            ->setParameters($parameters);
        
        return $qb->getQuery()->getResult();
    }
}
