<?php

namespace ABO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository{
    
    /*
     * shop:OfferType
     */
    public function getPayments($shop){
        
        $parameters = array('shop' => $shop,'active' => true);
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('p')
            ->from('ABOShopBundle:Payment', 'p')
            ->where('p.shop = :shop')
            ->andWhere('p.active = :active')
            ->setParameters($parameters);
        
        return $qb;
    }
}
