<?php

namespace ABO\ShopBundle\Entity;

/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends \Doctrine\ORM\EntityRepository {
    
    /*
     * Gallery
     */
    public function searchShops($nom){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('ABOShopBundle:Shop', 's')
            ->where($qb->expr()->like('s.name', ':nom'))
            ->addSelect('s')
            ->join('s.rateStat', 'r')
            ->addSelect('r')
            ->join('s.image', 'i')
            ->addSelect('i')
            ->join('s.address', 'a')
            ->addSelect('a')
            ->setParameter('nom', '%'.$nom.'%');
        return $qb->getQuery()
            ->getResult();
    }
    
    /*
     * Gallery
     */
    public function myFindAll(){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('ABOShopBundle:Shop', 's')
            ->addSelect('s')
            ->join('s.rateStat', 'r')
            ->addSelect('r')
            ->join('s.image', 'i')
            ->addSelect('i')
            ->join('s.address', 'a')
            ->addSelect('a');

        return $qb->getQuery()
            ->getResult();
    }
    
    /*
     * Shop:Show:home
     */
    public function getShop($slug) {
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('ABOShopBundle:Shop', 's')
            ->addSelect('s')
            ->join('s.rateStat', 'r')
            ->addSelect('r')
            ->join('s.image', 'i')
            ->addSelect('i');

        $qb->where('s.slug = :slug')
            ->setParameter('slug', $slug);
        
        return $qb->getQuery()
            ->getOneOrNullResult();
    }

    /*
     * Shop:Show:home
     */
    public function getShopWithCover($slug) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('ABOShopBundle:Shop', 's')
            ->addSelect('s')
            ->join('s.rateStat', 'r')
            ->addSelect('r')
            ->join('s.image', 'i')
            ->addSelect('i')
            ->join('s.cover', 'c')
            ->addSelect('c');

        $qb->where('s.slug = :slug')
            ->setParameter('slug', $slug);

        return $qb->getQuery()
            ->getOneOrNullResult();
    }

    /*
     * Shop:Show:home
     */
    public function getShopWithAddress($slug) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('ABOShopBundle:Shop', 's')
            ->addSelect('s')
            ->join('s.rateStat', 'r')
            ->addSelect('r')
            ->join('s.image', 'i')
            ->addSelect('i')
            ->join('s.address', 'a')
            ->addSelect('a');

        $qb->where('s.slug = :slug')
            ->setParameter('slug', $slug);

        return $qb->getQuery()
            ->getOneOrNullResult();
    }

    /*
     * Shop:Show:home
     */
    public function getShopCoverAddress($slug) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('ABOShopBundle:Shop', 's')
            ->addSelect('s')
            ->join('s.rateStat', 'r')
            ->addSelect('r')
            ->join('s.image', 'i')
            ->addSelect('i')
            ->join('s.cover', 'co')
            ->addSelect('co')
            ->join('s.address', 'a')
            ->addSelect('a');

        $qb->where('s.slug = :slug')
            ->setParameter('slug', $slug);

        return $qb->getQuery()
            ->getOneOrNullResult();
    }
}
