<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace ABO\AdminBundle\Controller;

/**
 * Description of Categories
 *
 * @author Aymen
 */
class Categories {
    
    public function getCategories(){
        
        $categories = [
            "automobiles and transportation" => $this->auto,
            "high-tech" => $this->high,
            "electronics" => $this->electronics,
            "home garden office pets" => $this->home,
            "clothing and prestige" => $this->clothing,
            "health and beauty" => $this->health,
            "entertainement and hobbies" => $this->entertainement,
            "antique and collectible" => $this->antique,
            //"food" => $this->food,
            //"books education and office" => $this->book,
            //"machinery tools and construction" => $this->machinery,
        ];
        
        return $categories;
    }
    
    public function getSizes(){
        
        return $this->sizes;
    }
    
    public function getColors(){
        
        return $this->colors;
    }
    
    private $colors = array(
        "FBEFEF","FBF2EF","FBF5EF","FBF8EF","FBFBEF","F8FBEF","F5FBEF","F2FBEF","EFFBEF","EFFBF2","EFFBF5","EFFBF8","EFFBFB","EFF8FB","EFF5FB","EFF2FB","EFEFFB","F2EFFB","F5EFFB","F8EFFB","FBEFFB","FBEFF8","FBEFF5","FBEFF2","FFFFFF",
        "F8E0E0","F8E6E0","F8ECE0","F7F2E0","F7F8E0","F1F8E0","ECF8E0","E6F8E0","E0F8E0","E0F8E6","E0F8EC","E0F8F1","E0F8F7","E0F2F7","E0ECF8","E0E6F8","E0E0F8","E6E0F8","ECE0F8","F2E0F7","F8E0F7","F8E0F1","F8E0EC","F8E0E6","FAFAFA",
        "F6CECE","F6D8CE","F6E3CE","F5ECCE","F5F6CE","ECF6CE","E3F6CE","D8F6CE","CEF6CE","CEF6D8","CEF6E3","CEF6EC","CEF6F5","CEECF5","CEE3F6","CED8F6","CECEF6","D8CEF6","E3CEF6","ECCEF5","F6CEF5","F6CEEC","F6CEE3","F6CED8","F2F2F2",
        "F5A9A9","F5BCA9","F5D0A9","F3E2A9","F2F5A9","E1F5A9","D0F5A9","BCF5A9","A9F5A9","A9F5BC","A9F5D0","A9F5E1","A9F5F2","A9E2F3","A9D0F5","A9BCF5","A9A9F5","BCA9F5","D0A9F5","E2A9F3","F5A9F2","F5A9E1","F5A9D0","F5A9BC","E6E6E6",
        "F78181","F79F81","F7BE81","F5DA81","F3F781","D8F781","BEF781","9FF781","81F781","81F79F","81F7BE","81F7D8","81F7F3","81DAF5","81BEF7","819FF7","8181F7","9F81F7","BE81F7","DA81F5","F781F3","F781D8","F781BE","F7819F","D8D8D8",
        "FA5858","FA8258","FAAC58","F7D358","F4FA58","D0FA58","ACFA58","82FA58","58FA58","58FA82","58FAAC","58FAD0","58FAF4","58D3F7","58ACFA","5882FA","5858FA","8258FA","AC58FA","D358F7","FA58F4","FA58D0","FA58AC","FA5882","BDBDBD",
        "FE2E2E","FE642E","FE9A2E","FACC2E","F7FE2E","C8FE2E","9AFE2E","64FE2E","2EFE2E","2EFE64","2EFE9A","2EFEC8","2EFEF7","2ECCFA","2E9AFE","2E64FE","2E2EFE","642EFE","9A2EFE","CC2EFA","FE2EF7","FE2EC8","FE2E9A","FE2E64","A4A4A4",
        "FF0000","FF4000","FF8000","FFBF00","FFFF00","BFFF00","80FF00","40FF00","00FF00","00FF40","00FF80","00FFBF","00FFFF","00BFFF","0080FF","0040FF","0000FF","4000FF","8000FF","BF00FF","FF00FF","FF00BF","FF0080","FF0040","848484",
        "DF0101","DF3A01","DF7401","DBA901","D7DF01","A5DF00","74DF00","3ADF00","01DF01","01DF3A","01DF74","01DFA5","01DFD7","01A9DB","0174DF","013ADF","0101DF","3A01DF","7401DF","A901DB","DF01D7","DF01A5","DF0174","DF013A","6E6E6E",
        "B40404","B43104","B45F04","B18904","AEB404","86B404","5FB404","31B404","04B404","04B431","04B45F","04B486","04B4AE","0489B1","045FB4","0431B4","0404B4","3104B4","5F04B4","8904B1","B404AE","B40486","B4045F","B40431","585858",
        "8A0808","8A2908","8A4B08","886A08","868A08","688A08","4B8A08","298A08","088A08","088A29","088A4B","088A68","088A85","086A87","084B8A","08298A","08088A","29088A","4B088A","6A0888","8A0886","8A0868","8A084B","8A0829","424242",
        "610B0B","61210B","61380B","5F4C0B","5E610B","4B610B","38610B","21610B","0B610B","0B6121","0B6138","0B614B","0B615E","0B4C5F","0B3861","0B2161","0B0B61","210B61","380B61","4C0B5F","610B5E","610B4B","610B38","610B21","2E2E2E",
        "3B0B0B","3B170B","3B240B","3A2F0B","393B0B","2E3B0B","243B0B","173B0B","0B3B0B","0B3B17","0B3B24","0B3B2E","0B3B39","0B2F3A","0B243B","0B173B","0B0B3B","170B3B","240B3B","2F0B3A","3B0B39","3B0B2E","3B0B24","3B0B17","1C1C1C",
        "2A0A0A","2A120A","2A1B0A","29220A","292A0A","222A0A","1B2A0A","122A0A","0A2A0A","0A2A12","0A2A1B","0A2A22","0A2A29","0A2229","0A1B2A","0A122A","0A0A2A","120A2A","1B0A2A","220A29","2A0A29","2A0A22","2A0A1B","2A0A12","151515",
        "190707","190B07","191007","181407","181907","141907","101907","0B1907","071907","07190B","071910","071914","071918","071418","071019","070B19","070719","0B0719","100719","140718","190718","190714","190710","19070B","000000",
    );

    private $sizes = array(
        'universal'=>array(
            'type'=>'uni','age'=>'al','sexe'=>'mf','clothe'=>'st',
            'values'=>['XXXS','XXS','XS','S','M','L','XL','XXL','XXXL'],
        ),
        'chaussure_homme'=>array(
            'type'=>'eur','age'=>'ad','sexe'=>'ml','clothe'=>'sh',
            'values'=>[35,35.5,36,36.5,37,37.5,38,38.5,39,40,41,42,43,43.5,44,44.5,45,45.5,46,46.5,47,47.5,48,48.5,49,50,51]
        ),
        'top-h'=>array(
            'type'=>'fr','age'=>'ad','sexe'=>'ml','clothe'=>'tp',
            'values'=>[34,36,38,40,42,44,46,48,50,52,54,56,58,60],
        ),
        'bas-h'=>array(
            'type'=>'fr','age'=>'ad','sexe'=>'ml','clothe'=>'bt',
            'values'=>[34,36,38,40,42,44,46,48,50,52,54],
        ),
        'top-f'=>array(
            'type'=>'fr','age'=>'ad','sexe'=>'fm','clothe'=>'tp',
            'values'=>[32,34,36,38,40,42,44,46,48,50,52,54],
        ),
        'bas-f'=>array(
            'type'=>'fr','age'=>'ad','sexe'=>'fm','clothe'=>'bt',
            'values'=>[30,32,34,36,38,40,42,44,46,48,50,52,54,56],
        ),
        'panties-f'=>array(
            'type'=>'fr','age'=>'ad','sexe'=>'fm','clothe'=>'pn',
            'values'=>[60,65,70,75,80,85,90,95,100,105,110],
        ),
        'sg-f'=>array(
            'type'=>'eur','age'=>'ad','sexe'=>'fm','clothe'=>'sg',
            'values'=>['75A','80A','85A','90A','95A',
                    '75B','80B','85B','90B','95B','100B','105B','110B','115B','120B','125B','130B','135B',
                    '85C','90C','95C','100C','105C','110C','115C','120C','125C','130C','135C',
                    '85D','90D','95D','100D','105D','110D','115D','120D','125D','130D','135D',
                    '85E','90E','95E','100E','105E','110E','115E','120E','125E','130E','135E',
                    '90F','95F','100F','105F','110F','115F','120F','125F','130F','135F',
                    '100G','105G','110G','115G','120G','125G','130G','135G',
                    '100H','105H','110H','115H','120H','125H','130H','135H',
                ],
        ),
        'chaussure-f'=>array(
            'type'=>'eur','age'=>'ad','sexe'=>'fm','clothe'=>'sh',
            'values'=>[35,35.5,36,36.5,37,37.5,38,38.5,39,40,41,42,43,43.5,44,44.5,45]
        ),
        'children-shoes'=>array(
            'type'=>'eur','age'=>'tn','sexe'=>'mf','clothe'=>'sh',
            'values'=>[17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35],
        ),
        'top-child-h'=>array(
            'type'=>'eur','age'=>'tn','sexe'=>'ml','clothe'=>'st',
            'values'=>[86,94,102,108,114,120,126,132,138,150,162,174],
        ),
        'top-child-f'=>array(
            'type'=>'eur','age'=>'tn','sexe'=>'fm','clothe'=>'st',
            'values'=>[86,94,102,108,114,120,126,132,138,150,156,162],
        ),
        'top-child'=>array(
            'type'=>'age','age'=>'tn','sexe'=>'mf','clothe'=>'st',
            'values'=>['2A','3A','4A','5A','6A','7A','8A','9A','10A','12A','14A','16A'],
        ),
        'baby-age'=>array(
            'type'=>'age','age'=>'bb','sexe'=>'mf','clothe'=>'st',
            'values'=>['0M','1M','2M','3M','6M','9M','12M','18M','24M'],
        ),
        'baby-shoes'=>array(
            'type'=>'fr','age'=>'bb','sexe'=>'mf','clothe'=>'sh',
            'values'=>[17,18,19,20,21,22,23,24,25,26,27,28,29,30],
        ),
    );
    // complete
    private $high = array(
        "Phone and Cellphone"=>[
            "Cellphone"                             =>"Standard",
            "Smartphone"                            =>"PhoneTablet",
            "Phone"                                 =>"Standard",
            "Fax"                                   =>"Standard",
            "Phone Cellphone Accessories and Parts" =>"Standard"
        ],
        "Computers"=>[
            "Laptop"                                =>"Computer",
            "Gamer"                                 =>"Computer",
            "Desktops"                              =>"Computer",
            "All-in-One"                           =>"Computer",
            "Server"                               =>"Computer",
        ],
        "Tablets"=>[
            "Tablet"                                =>"PhoneTablet",
            "Tablet Accessories"                    =>"Standard"
        ],
        'Wearable Technology' => [
            "Activity Trackers"                     =>"Standard",
            "Wearable Cameras"                      =>"Standard",
            "Smart Glasses"                         =>"Standard",
            "Smart Watches"                         =>"Standard",
            "For Kids"                              =>"Standard",
            "Smart Sport Accessories"               =>"Standard",
            "Healthcare Devices"                    =>"Standard",
            "Gesture Control & Entertainment"       =>"Standard",
        ],
        "Cameras and Camcorders"=>[
            "Camcorder"                            =>"Camcorder",
            "Digital Camera"                       =>"Camera",
            "Camera Flash"                          =>"Standard",
            "Lenses and Filters"                    =>"Standard",
            "Binoculars"                            =>"Standard",
            "Camera Parts and Tools"                =>"Standard",
            "Camera and Camcorder Accessories"    =>"Standard"
        ],
        "PC Components"=>[
            "Screen"                                =>"Monitor",
            "Processors"                            =>"Processor",
            "Motherboards"                          =>"Motherboard",
            "Graphics Cards"                        =>"GraphicCard",
            "Internal Storage"                      =>"Storage",
            "RAM"                                   =>"Ram",
            "Coolers and Fans"                      =>"Standard",
            "Power Supplies"                        =>"Standard", 
            "Case"                                  =>"Standard",
            "Burner Readers"                        =>"Standard",
            "Controller Cards"                      =>"Standard",
            "Sound Cards"                           =>"Standard",
            "TV Tuner Cards"                        =>"Standard",
            "Computer and Server Racks"             =>"Standard",
            "Other PC Components"                   =>"Standard"
        ],
        "Printers and Ink"=>[
            "Inkjet Printers"                       =>"Standard", 
            "Laser Printers"                        =>"Standard",
            "Photo Printers"                        =>"Standard", 
            "Scanners"                              =>"Standard", 
            "3D Printers"                           =>"Standard",
            "Printer and Ink Accessories and Parts" =>"Standard"
        ],
        "Software"=>[
            "Antivirus and Security"                =>"Standard", 
            "Office Software"              =>"Standard",
            "Multimedia Software"                   =>"Standard",
            "Leisure and Practical Life Software"   =>"Standard",
            "professional Software"                 =>"Standard",
            "Mac Software"                          =>"Standard"
        ],
        "Networking"=>[
            "WiFi USB Key"                          =>"Standard",
            "Bluetooth USB Key"                     =>"Standard",
            "Modems and Routers"                    =>"Standard", 
            "PLC Adapters"                          =>"Standard",
            "WiFi Booster"                          =>"Standard", 
            "WiFi Repeater"                         =>"Standard", 
            "WiFi Extender"                         =>"Standard", 
            "NAS Storage Servers"                   =>"Standard",
            "Networking Accessories"                =>"Standard",
            "Other Networking Products"              =>"Standard"
        ],
        "PC Accessories"=>[
            "Keyboard"                              =>"Standard",
            "Mouse"                                 =>"Standard",
            "Mousepad"                              =>"Standard",
            "PC Speakers"                           =>"Standard",
            "Webcams"                               =>"Standard",
            "Storage"                               =>"Storage",
            "Microphone"                            =>"Standard",
            "Graphic Tablets and Pens"              =>"Standard",
            "Other PC Accessories"              =>"Standard"
        ],
    );
    // complete
    private $electronics = array(
        "TV and Projectors"=>[
            "TV"                                    =>"Television", 
            "Projectors"                            =>"Projector", 
            "DTT and Satellite"                     =>"Standard", 
            "Mounts"                                =>"Standard",
            "accessories TV and Projectors"         =>"Standard"
        ],
        "Hi-Fi and Home Theater"=>[
            "Home Theater"                          =>"Standard",
            "Sound Bars"                            =>"Standard", 
            "Micro System and Mini System"          =>"Standard", 
            "Hi-Fi"                                 =>"Standard",
            "Speakers"                              =>"Standard",
            "Headphones and Earphones"              =>"Standard", 
            "Car Audio"                             =>"Standard",
            "Radio and Alarm Clock"                 =>"Standard"
        ],
        "Audio and Video"=>[
            "CD Player"                             =>"Standard",
            "MP3 Player"                            =>"Standard",
            "MP4 Player"                            =>"Standard",
            "Blu-Ray Player"                        =>"Standard",
            "DVD Player"                            =>"Standard",
            "Sound Recorder"                        =>"Standard",
            "Audio Video Accessories"               =>"Standard"
        ],
        "Radio Communication"=>[
            "CB Radios"                             =>"Standard", 
            "Radio Antennas"                        =>"Standard", 
            "Radio Scanners"                        =>"Standard",
            "Walkie Talkies"                        =>"Standard"
        ],
        "Batteries and Power"=>[
            "Batteries"                             =>"Standard",
            "Batteries Charger"                     =>"Standard",
            "Batteries and Power Accessories"       =>"Standard"
        ],
    );
    // complete
    private $clothing = array(
        'men clothing'=> [
            'Jacket'                           =>"TopMan",
            'Bermuda'                           =>"BottomMan",
            'Shirt'                           =>"TopMan",
            'Coat'                           =>"TopMan", 
            'Pull'                              =>"TopMan",
            'Vest'                             =>"TopMan",
            'Hoodie'                             =>"TopMan",
            'T-Shirt'                           =>"TopMan",
            'Polo'                              =>"TopMan",
            'Blazers'                             =>"TopMan",
            'Jean'                              =>"BottomMan",
            'Pants'                          =>"BottomMan",
            'Capri Pants'                        =>"BottomMan", 
            'Short'                             =>"BottomMan",
            'Swimsuit'                   =>"BottomMan",
            'Pajamas'                            =>"TopMan",
            'Dressing Gown'                   =>"TopMan",
            'Underwear'                    =>"BottomMan",
            'Sportswear'                        =>"TopMan",
            'Shoes'                             =>"ShoesMan",
            'Suit'                              =>"TopMan",
            'Workwear'                          =>"TopMan",
        ],
        'women clothing'=> [
            'Dress'                            =>"TopWoman",
            'Combination'                     =>"TopWoman",
            'Swimsuit'                 =>"UnderwearWoman",
            'Tank Top'                       =>"TopWoman",
            'Vest'                           =>"TopWoman",
            'Jean'                            =>"BottomWoman",
            'Pants'                        =>"BottomWoman",
            'Short'                           =>"BottomWoman",
            'Capri Pants'                      =>"BottomWoman",
            'Lingerie'                        =>"UnderwearWoman",
            'Bras'                            =>"UnderwearWoman",
            'Panties'                         =>"UnderwearWoman",
            'Pull'                            =>"TopWoman",
            'Bib & Brace'                       =>"TopWoman",
            'T-Shirt'                         =>"TopWoman",
            'Shirt'                         =>"TopWoman",
            'Skirt'                            =>"TopWoman",
            'Blazers'                           =>"TopWoman",
            'Underwear'                  =>"UnderwearWoman",
            'Pajamas'                          =>"TopWoman",
            'Sportswear'                      =>"TopWoman",
            'Shoes'                           =>"ShoesWoman",
            'Workwear'                        =>"TopWoman",
            'Nightgown'                  =>"TopWoman",
            'Dressing Gown'                   =>"TopWoman",
        ],
        'girls clothing'=>[
            'Coat'                          =>"TopGirl",
            'Jacket'                          =>"TopGirl",
            'Pull'                             =>"TopGirl",
            'Hoodie'                            =>"TopGirl",
            'Vest'                            =>"TopGirl",
            'T-Shirt'                          =>"TopGirl",
            'Tank Top'                        =>"TopGirl",
            'Blouse'                           =>"TopGirl",
            'Dress'                             =>"TopGirl",
            'Skirt'                             =>"BottomGirl",
            'Jean'                             =>"BottomGirl",
            'Pants'                         =>"BottomGirl",
            'Capri Pants'                       =>"BottomGirl",
            'Legging'                          =>"BottomGirl",
            'Jogging'                          =>"BottomGirl",
            'Bib & Brace'                        =>"TopGirl",
            'Combination'                      =>"TopGirl",
            'Short'                            =>"BottomGirl",
            'Bermuda'                          =>"TopGirl",
            'Swimsuit'                  =>"TopGirl",
            'Pajamas'                           =>"TopGirl",
            'Nightgown'                  =>"TopGirl",
            'Dressing Gown'                   =>"TopGirl",
            'Underwear'                   =>"TopGirl",
            'Tights'                         =>"TopGirl",
            'Sportswear'                       =>"TopGirl",
            'Shoes'                            =>"ShoesGirl",
            'Schoolwear'                       =>"TopGirl",
        ],
        'boys clothing'=>[
            'Coat'                           =>"TopBoy",
            'Jacket'                           =>"TopBoy",
            'Pull'                              =>"TopBoy",
            'Hoodie'                             =>"TopBoy",
            'Vest'                             =>"TopBoy",
            'T-Shirt'                           =>"TopBoy",
            'Polo'                              =>"TopBoy",
            'Shirt'                           =>"TopBoy",
            'Jean'                              =>"BottomBoy",
            'Pants'                          =>"BottomBoy",
            'Capri Pants'                        =>"BottomBoy",
            'Jogging'                           =>"BottomBoy",
            'Short'                             =>"BottomBoy",
            'Bermuda'                           =>"BottomBoy",
            'Swimsuit'                   =>"BottomBoy",
            'Pajamas'                            =>"TopBoy",
            'Underwear'                    =>"TopBoy",
            'Sportswear'                        =>"TopBoy",
            'Shoes'                             =>"ShoesBoy",
            'Schoolwear'                        =>"TopBoy",
            'Dressing Gown'                   =>"TopGirl",
        ],
        'babies clothing'=>[
            'Set'                         =>"TopBaby",
            'Pajamas'                           =>"TopBaby",
            'Coat'                          =>"TopBaby",
            'T-shirt'                          =>"TopBaby",
            'Tunic'                          =>"TopBaby",
            'Blouse'                           =>"TopBaby",
            'Pull'                             =>"TopBaby",
            'Vest'                            =>"TopBaby",
            'Hoodie'                            =>"TopBaby",
            'Dress'                             =>"TopBaby",
            'Skirt'                             =>"TopBaby",
            'Pants'                         =>"TopBaby",
            'Jeans'                             =>"TopBaby",
            'Short'                            =>"TopBaby",
            'Combination'                      =>"TopBaby",
            'Bib & Brace'                        =>"TopBaby",
            'Tights'                         =>"BottomBaby",
            'Swimsuit'                  =>"TopBaby",
            'Sleeping bag'                        =>"TopBaby",
            'Dressing Gown'                   =>"TopGirl",
            'Shoes'                            =>"ShoesBaby",
        ],
        'clothing accessories'=>[
            'Umbrella'                             =>"Standard",
            'Maternity Suitcase'                      =>"Standard",
            'Scarf'                      =>"Standard",
            'Hat, Cap'                               =>"Standard",
            'Bonnet'                                =>"Standard",
            'Gloves'                                 =>"Standard",
            'Belts'                              =>"Standard",
            'Handbags'                            =>"Standard",
            'Wallets'                                =>"Standard",
            'Tie'                               =>"Standard",
            'Socks'                           =>"Standard",
            'Angel Nest'                            =>"Standard",
            
        ],
        "men watches and jewelry" =>[
            'Wedding Bands'                     =>"Standard",
            'Watches'                           =>"Standard",
            'Cufflinks and Shirt Studs'           =>"Standard",
            'Blazer Buttons'                    =>"Standard",
            'Necklaces'                         =>"Standard",
            'Bracelets'                         =>"Standard",
            'Rings'                             =>"Standard",
        ] ,
        "women watches and jewelry" =>[
            'Anklets'                         =>"Standard",
            'Bracelets'                       =>"Standard",
            'Brooches & Pins'                 =>"Standard",
            'Earrings'                        =>"Standard",
            'Jewelry Sets'                    =>"Standard",
            'Necklaces'                       =>"Standard",
            'Wedding Bands'                   =>"Standard",
            'Watches'                         =>"Standard",
        ] ,
        "children watches and jewelry" =>[
            'Watches'                      =>"Standard",
            'Anklets'                      =>"Standard",
            'Bracelets'                    =>"Standard",
            'Earrings'                     =>"Standard",
            'Necklaces'                    =>"Standard",
        ] ,
        "bags and luggage" =>[
            'Suitcases'                       =>"Standard",
            'Backpacks and Sports Bags'       =>"Standard",
            'Childrens Luggage'               =>"Standard",
            'Shopping Trolleys'               =>"Standard",
            'Suit Carriers'                   =>"Standard",
            'Briefcases'                      =>"Standard",
            'Holdalls'                         =>"Standard",
            'shoulder Bags'                  =>"Standard",
            'Bags and Luggage Accessories'  =>"Standard",
        ] ,
    );
    // complete
    private $home = array( 
        "Small Appliances" =>[
            'Coffee, Tea & Espresso'         =>    'Standard',
            'Blenders & Juicers'              =>    'Standard',
            'Mixers & Mixer Accessories'    =>    'Standard',
            'Toasters'                         =>    'Standard',
            'Electric Griddles & Hotplates'  =>   'Standard',
            'Food Processors'                 =>    'Standard',
            'Other Appliances'                =>    'Standard',
        ] ,
        "Major Appliances" =>[
            'Dishwashers'                               =>  'Standard',
            'Dishwasher Parts & Accessories'        =>  'Standard',
            'Microwave Ovens'                         =>'Standard',
            'Microwave Ovens Parts & Accessories'   =>  'Standard',
            'Refrigerators & Freezers'                  =>'Standard',
            'Washers & Dryers'                          =>'Standard',
            'Pizza Ovens'                               =>'Standard',
        ] ,
        "Furniture" =>[
            'Armoires & WardDresss'                          =>'Standard',
            'Chairs, Bar Stools & Benches'                  =>'Standard',
            'Bean Bags & Inflatables'                       =>'Standard',
            'Beds & Mattresses'                             =>'Standard',
            'Bedroom Sets'                                  =>'Standard',
            'Bookcases'                                         =>'Standard',
            'Cabinet & Cupboards'                               =>'Standard',
            'Desks & Home Office Furniture'                 =>'Standard',
            'Dining Sets'                                       =>'Standard',
            'Dressers & Chests of Drawers'                   =>'Standard',
            'Entertainment Units, TV Stands'                =>'Standard',
            'Futons & Covers'                                   =>'Standard',
            'Nightstands'                                       =>'Standard',
            'Ottomans, Footstools & Poufs'                  =>'Standard',
            'Screens & Room Dividers'                       =>'Standard',
            'Slipcovers'                                        =>'Standard',
            'Sofas, Loveseats'                                  =>'Standard',
            'Tables'                                            =>'Standard',
            'Trunks & Chests'                                   =>'Standard',
            'Vanities & Makeup Tables'                          =>'Standard',
            'Furniture Parts & Accessories'                 =>'Standard',
            'Other Home Furniture'                              =>'Standard',
        ] ,
        'Home Décor'=>[
            'Afghans & Throw Blankets'                      =>'Standard',
            'Baskets'                                           =>'Standard',
            'Bookends'                                          =>'Standard',
            'Bottles'                                           =>'Standard',
            'Boxes, Jars & Tins'                              =>'Standard',
            'Candles, Candle Holders & Accessories'         =>'Standard',
            'carpets and rugs'                                 =>'Standard',
            'Clocks'                                            =>'Standard',
            'Decals, Stickers & Vinyl Art'                   =>'Standard',
            'Decorative Fruit & Vegetables'                  =>'Standard',
            'Floral Décor'                                      =>'Standard',
            'Frames'                                            =>'Standard',
            'Home Fragrances'                                   =>'Standard',
            'Mirrors'                                           =>'Standard',
            'Pillows'                                           =>'Standard',
            'Plate Racks & Hangers'                             =>'Standard',
            'Posters & Prints'                                  =>'Standard',
            'Tapestries'                                        =>'Standard',
            'Vases'                                             =>'Standard',
            'Wall Shelves'                                      =>'Standard',
            'Other Home Décor'                                 =>'Standard',
        ],
        "Linens" =>[
            'Apron'                                             =>'Standard',
            'Bed Linens'                                        =>'Standard',
            'Blanket'                                           =>'Standard',
            'Dish Towel & Napkin'                               =>'Standard',
            'Oven Glove'                                        =>'Standard',
            'Tablecloth & Table Runners'                       =>'Standard',
            'Towel'                                             =>'Standard',
            'Other Linens'                                             =>'Standard',
        ] ,
        "Lighting" =>[
            'Chandeliers'                                       =>'Standard',
            'Lamps & Lamp Shades'                               =>'Standard',
            'Light Bulbs'                                       =>'Standard',
            'Night Lights '                                     =>'Standard',
            'String Lights, Fairy Lights'                     =>'Standard',
            'Wall Fixtures '                                    =>'Standard',
            'Lighting Parts & Accessories'                   =>'Standard',
            'Other Lighting'                                   =>'Standard',
        ] ,
        "Sanitary and Plumbing" =>[
            'Shower'                                            =>'Standard',
            'Bathtub'                                           =>'Standard',
            'Toilet'                                            =>'Standard',
            'Washbasin'                                         =>'Standard',
            'Bidet'                                             =>'Standard',
            'Faucets'                                           =>'Standard',
            'Accessories'                                       =>'Standard',
        ] ,
        "HVAC" =>[
            'Air Conditioners & Coolers'                      =>'Standard',
            'Air Filters'                                       =>'Standard',
            'Air Purifiers'                                     =>'Standard',
            'Fireplace & Hearth'                                =>'Standard',
            'HVAC Parts & Accessories'                          =>'Standard',
            'Heaters'                                             =>'Standard',
            'Portable Fans'                                      =>'Standard',
            'Thermostats'                                        =>'Standard',
            'Ventilation'                                        =>'Standard',
            'Water Heaters'                                      =>'Standard',
        ] ,
        "Garden and Outdoors" =>[
            'Garden Décor'                                       =>'Standard',
            'Gardening Supplies'                                =>'Standard',
            'Lawnmowers'                                          =>'Standard',
            'Outdoor Cooking & Eating'                         =>'Standard',
            'Patio & Garden Furniture'                          =>'Standard',
            'Plants, Seeds & Bulbs'                             =>'Standard',
            'Pools, Pools Parts & Accessories'                 =>'Standard',
        ] ,
        "Pets" =>[
            'Birds & Supplies'                                  =>'Standard',
            'Cats & Supplies'                                   =>'Standard',
            'Dogs & Supplies'                                   =>'Standard',
            'Fish & Supplies'                                   =>'Standard',
            'Other Pets & Supplies '                            =>'Standard',
        ] ,
        "House Cleaning" =>[
            'Carpet Shampooers & Steamers'                      =>'Standard',
            'Carpet & Floor Sweepers'                            =>'Standard',
            'Cleaning Products'                                   =>'Standard',
            'Cleaning Towels & Cloths'                           =>'Standard',
            'Laundry Supplies'                                    =>'Standard',
            'Mops & Brooms'                                       =>'Standard',
            'Paper Products'                                       =>'Standard',
            'Trash Cans & Wastebaskets'                           =>'Standard',
            'Vacuum Cleaners'                                      =>'Standard',
            'Vacuum Parts & Accessories'                          =>'Standard',
            'Other Home Cleaning Supplies'                       =>'Standard',
        ] ,
        "Cookware and Tableware" =>[
            'Saucepans'                                             =>'Standard',
            'Frying Pans'                                           =>'Standard',
            'Copper Cookware'                                      =>'Standard',
            'Casseroles'                                            =>'Standard',
            'Roasters & Racks'                                     =>'Standard',
            'Griddles & Grill Pans'                                =>'Standard',
            'Oven-to-tableware'                                    =>'Standard',
            'Sauté Pans'                                            =>'Standard',
            'Stockpots'                                             =>'Standard',
            'Woks'                                                   =>'Standard',
            'Steamers & Bain-Maries'                              =>'Standard',
            'Stovetop Kettles'                                      =>'Standard',
            'Egg Poachers'                                          =>'Standard',
            'Induction Cookware'                                   =>'Standard',
            'Tableware'                                              =>'Standard',
            'Tagines'                                                =>'Standard',
            'Other Cookware'                                        =>'Standard',
        ] ,
        "Security and Protection" =>[
            'Access Control'                                        =>'Standard',
            'Alarms'                                                 =>'Standard',
            'Locks'                                                  =>'Standard',
            'Security Cameras'                                      =>'Standard',
            'Door Security'                                         =>'Standard',
            'Safes'                                                   =>'Standard',
            'Key Hiders'                                             =>'Standard',
            'Security Lighting'                                     =>'Standard',
            'Other Home Security Gadgets'                         =>'Standard',
        ] ,
    );
    // complete
    private $health = array(
        "bath and body" =>[
            'Body Moisturisers'        =>'Standard',
            'Body Cleansers'            =>'Standard',
            'Body Scrubs'               =>'Standard',
            'Beautifying Oil'          =>'Standard',
            'Hands & Feet'          =>'Standard',
            'Spa & Treatment'           =>'Standard',
            'Aromatherapy & Massage'        =>'Standard',
            'Bath & Body ACCESSORIES'       =>'Standard',
            'Other Bath & Body Products'    =>'Standard',
        ] ,
        "Hair Care For Him" =>[
            'Shampoo'                   =>'Standard',
            'Conditioner'               =>'Standard',
            'Hair Treatment'            =>'Standard',
            'Hair Styling'              =>'Standard',
            'Brushes & Combs'           =>'Standard',
        ] ,
        "Hair Care For Her" =>[
            'Shampoo'                       =>'Standard',
            'Conditioner'                   =>'Standard',
            'Hair Treatment'                =>'Standard',
            'Hair Styling'                  =>'Standard',
            'Brushes & Combs'               =>'Standard',
        ] ,
        "Makeup" =>[
            'Spring Trend'                  =>'Standard',
            'All-In-One'                     =>'Standard',
            'Face'                            =>'Standard',
            'Eyes'                            =>'Standard',
            'Cheeks'                          =>'Standard',
            'Lips'                            =>'Standard',
            'Bronzing'                       =>'Standard',
            'Brushes & Tools'               =>'Standard',
            'Nails'                           =>'Standard',
        ] ,
        "Skin Care" =>[
            'Cleansers'                     =>'Standard',
            'Exfoliators & Masks'           =>'Standard',
            'Toners'                        =>'Standard',
            'Serums'                        =>'Standard',
            'Moisturisers'                  =>'Standard',
            'Eye Care'                      =>'Standard',
            'Lip Care'                      =>'Standard',
            'Accessories'                   =>'Standard',
        ] ,
        "Oral Care" =>[
            'Dentures'                      =>'Standard',
            'Flosses'                       =>'Standard',
            'Mouthwash'                     =>'Standard',
            'Toothbrushes'                  =>'Standard',
            'Toothpaste'                    =>'Standard',
            'Sensitivity'                   =>'Standard',
            'Whitening'                     =>'Standard',
        ] ,
        "Baby Care" =>[
            'Baby Wash'                     =>'Standard',
            'Bubble Bath'                   =>'Standard',
            'Cologne'                       =>'Standard',
            'Cotton'                        =>'Standard',
            'Diaper Cream'                 =>'Standard',
            'Gift Packs'                    =>'Standard',
            'Haircare'                      =>'Standard',
            'Lotion'                        =>'Standard',
            'Nursing Pads'                  =>'Standard',
            'Oil'                            =>'Standard',
            'Powder'                        =>'Standard',
            'Wipes'                         =>'Standard',
        ] ,
        "Fragrance For Him" =>[
            'Aftershave'                    =>'Standard',
            'Deodorant'                     =>'Standard',
            'Eau De Toilette & Parfum'    =>'Standard',
            'Alcohol Free'                  =>'Standard',
        ] ,
        "Fragrance For Her" =>[
            'Deodorant'                     =>'Standard',
            'Eau De Toilette & Parfum'    =>'Standard',
            'Alcohol Free'                  =>'Standard',
        ] ,
        "Vision Care" =>[
            'Eyeglasses'                    =>'Standard',
            'Eyeglass Lenses'               =>'Standard',
            'Frame Styles'                  =>'Standard',
            'Sunglasses'                    =>'Standard',
            'Anti-Reflective Lenses'       =>'Standard',
            'Body'                           =>'Standard',
        ] ,
    );
    // complete
    private $entertainement = array(
        "Video Games and Consoles" =>[
            "Consoles"              =>"Console",
            "video games"           =>"Standard",
            "Gaming Accessories"  =>"Standard",
        ] ,
        "Musical Instruments" =>[
            'Brass'                 => 'Standard',
            'Percussion'            => 'Standard',
            'Strings'               => 'Standard',
            'Woodwinds'             => 'Standard',
        ] ,
        "Sports" =>[
            'Football'              => 'Standard',
            'BasketBall'            => 'Standard',
            'Cycling'               => 'Standard',
            'Brass'                 => 'Standard',
            'Sports'                => 'Standard',
        ] ,
        "Movies and TV Series" =>[
            'Movies'                => 'Standard',
            'TV Series'             => 'Standard',
        ] ,
        "Games and Toys" =>[
            'Building Toys'         => 'Standard',
            'Dolls & Puppets'       => 'Standard',
            'Electronic Games'      => 'Standard',
            'Learning & Education' => 'Standard',
            'Puzzles'                 => 'Standard',
            'Sports & Outdoor Play' => 'Standard',
            'Other'                   => 'Standard',
        ],
    );
    // complete
    private $antique = array(
        "Automobiles " =>[
            'Sports Cars'=>'Standard',
            'Luxury Cars'=>'Standard',
            'Large Cars'=>'Standard',
            'Midsize Cars'=>'Standard',
            'Small Cars'=>'Standard',
            'Trucks'=>'Standard',
            'Motorcycles'=>'Standard',
            'Bikes'=>'Standard',
        ] ,
        "Arts" =>[
            'Painting'                 => 'Standard',
            'Sculpting'            => 'Standard',
            'Photography'               => 'Standard',
            'Calligraphy'             => 'Standard',
            'Mosaic'             => 'Standard',
        ] ,
        "Books and Manuscripts" =>[
            'Agriculture'                   => 'Book',
            'Architecture'                  => 'Book',
            'Art'                           => 'Book',
            'Biography and Memoir'      => 'Book',
            'Business'                  => 'Book',
            'Children Fiction'          => 'Book',
            'Children Non-Fiction'      => 'Book',
            'Cooking and Food'          => 'Book',
            'Crafts and Hobbies'        => 'Book',
            'Family and Parenting'      => 'Book',
            'Fiction'                   => 'Book',
            'Fun and Games'             => 'Book',
            'Gardening'                 => 'Book',
            'Health, Mind, and Body'    => 'Book',
            'History'                       => 'Book',
            'Home Reference / How-To'   => 'Book',
            'Humor'                         => 'Book',
            'Magasine'                      => 'Book',
            'Medical'                       => 'Book',
            'Music'                         => 'Book',
            'Newspapers'                    => 'Book',
            'Performing Arts'               => 'Book',
            'Pets'                          => 'Book',
            'Philosophy'                    => 'Book',
            'Photography'                   => 'Book',
            'Reference'                     => 'Book',
            'Religion'                      => 'Book',
            'Self-Help'                     => 'Book',
            'Social Science'                => 'Book',
            'Sports and Recreation'         => 'Book',
            'Transportation'                => 'Book',
            'Travel'                        => 'Book',
        ] ,
        "Furniture and Décor" =>[
            'Armoires & WardDresss'                          =>'Standard',
            'Chairs, Bar Stools & Benches'                  =>'Standard',
            'Bean Bags & Inflatables'                       =>'Standard',
            'Beds & Mattresses'                             =>'Standard',
            'Bookcases'                                         =>'Standard',
            'Cabinet & Cupboards'                               =>'Standard',
            'Desks & Home Office Furniture'                 =>'Standard',
            'Dining Sets'                                       =>'Standard',
            'Entertainment Units, TV Stands'                =>'Standard',
            'Ottomans, Footstools & Poufs'                  =>'Standard',
            'Sofas, Loveseats'                                  =>'Standard',
            'Tables'                                            =>'Standard',
            'Afghans & Throw Blankets'                      =>'Standard',
            'Candles, Candle Holders & Accessories'         =>'Standard',
            'carpets and rugs'                                 =>'Standard',
            'Clocks'                                            =>'Standard',
            'Decals, Stickers & Vinyl Art'                   =>'Standard',
            'Floral Décor'                                      =>'Standard',
            'Frames'                                            =>'Standard',
            'Mirrors'                                           =>'Standard',
            'Vases'                                             =>'Standard',
        ] ,
        "Musical Instruments" =>[
            'Brass'                 => 'Standard',
            'Percussion'            => 'Standard',
            'Strings'               => 'Standard',
            'Woodwinds'             => 'Standard',
        ] ,
        "Lighting" =>[
            'Indoor'               => 'Standard',
            'Outdoor'             => 'Standard',
        ] ,
        "Jewelry" =>[
            'Women Jewelry'  => 'Standard',
            'Men Jewelry'  => 'Standard',
            'Women Watches'  => 'Standard',
            'Men Watches'  => 'Standard',
        ] ,
        "Clothing" =>[
            'Men'  => 'Standard',
            'Women'  => 'Standard',
            'Girl'  => 'Standard',
            'Boy'  => 'Standard',
            'Baby'  => 'Standard',
        ] ,
        "Ceramics and Pottery" =>[
            'Ceramics'  => 'Standard',
            'Pottery'  => 'Standard',
        ],
    );
    // complete
    private $auto = array(
        "Cars" =>[
            'Sports'=>'Auto',
            'Luxury'=>'Auto',
            'Large'=>'Auto',
            'Midsize'=>'Auto',
            'Small'=>'Auto',
        ] ,
        "Trucks" =>[
            'Light Duty'=>'Auto',
            'Medium Duty'=>'Auto',
            'Heavy Duty'=>'Auto',
        ] ,
        "Motorcycles and Bikes" =>[
            'Motorcycles'=>'Moto',
            'Bikes'=>'Standard',
        ] ,
        "Parts Electronics and Accessories" =>[
            'Car Parts'=>'Standard',
            'Motorcycles Parts'=>'Standard',
            'Bikes Parts'=>'Standard',
            'Car Electronics'=>'Standard',
            'Motorcycles Electronics'=>'Standard',
            'Car Accessories'=>'Standard',
            'Motorcycles Accessories'=>'Standard',
            'Bikes Accessories'=>'Standard',
        ] ,
    );


    // uncomplete / after deploy
    private $food = array(
        "meats" =>[

        ] ,
        "fishes" =>[

        ] ,
        "dairy products" =>[

        ] ,
        "fats and oils" =>[

        ] ,
        "vegetables and fruits" =>[

        ] ,
        "cereals" =>[

        ] ,
        "sugars" =>[

        ] ,
        "pastry" =>[

        ] ,
        "beverages" =>[

        ] ,
    );
    // uncomplete / after deploy
    private $book = array(
        "books magazines and newspapers" =>[
            'AGRICULTURE' => 'Standard',
            'ARCHITECTURE' => 'Standard',
            'ART' => 'Standard',
            'BIOGRAPHY and MEMOIR' => 'Standard',
            'BUSINESS' => 'Standard',
            'CHILDREN FICTION' => 'Standard',
            'CHILDREN NON-FICTION' => 'Standard',
            'COOKING and FOOD' => 'Standard',
            'CRAFTS and HOBBIES' => 'Standard',
            'FAMILY and PARENTING' => 'Standard',
            'FICTION' => 'Standard',
            'FUN and GAMES' => 'Standard',
            'GARDENING' => 'Standard',
            'HEALTH, MIND, and BODY' => 'Standard',
            'HISTORY' => 'Standard',
            'HOME REFERENCE / HOW-TO' => 'Standard',
            'HUMOR' => 'Standard',
            'Magasine' => 'Standard',
            'MEDICAL' => 'Standard',
            'MUSIC' => 'Standard',
            'Newspapers' => 'Standard',
            'PERFORMING ARTS' => 'Standard',
            'PETS' => 'Standard',
            'PHILOSOPHY' => 'Standard',
            'PHOTOGRAPHY' => 'Standard',
            'REFERENCE' => 'Standard',
            'RELIGION' => 'Standard',
            'SELF-HELP' => 'Standard',
            'SOCIAL SCIENCE' => 'Standard',
            'SPORTS and RECREATION' => 'Standard',
            'TRANSPORTATION' => 'Standard',
            'TRAVEL' => 'Standard',
        ] ,
        "livres Scolaire et Parascolaire" =>[
            'math' => 'Standard',
            'physique' => 'Standard',
            'gestion et finance' => 'Standard',
            'economie' => 'Standard',
            'histoire et geographie' => 'Standard',
            'langues' => 'Standard',
            'religion' => 'Standard',
            'science vie terre' => 'Standard',
            'technologie' => 'Standard',
            'informatique' => 'Standard',
            'mecanique' => 'Standard',
            'medicine' => 'Standard',
            'philosophie' => 'Standard',
            'other' => 'Standard',
        ] ,
        "bags and kits" =>[
            'stylos bag' => 'Standard',
            'school bag' => 'Standard',
        ] ,
        "Stationery and Agendas" =>[

        ] ,
        "writing" =>[
            'stylos' => 'Standard',
        ] ,
        "Office organisation" =>[

        ] ,
        "Drawing" =>[

        ] ,
        "Documents ranking" =>[

        ] ,
        "scholar tools" =>[

        ] ,
    );
    // uncomplete / later
    private $machinery = array(
        "Air Compressors" => [
            'Breathable',
            'Centrifugal',
            'Dryers',
            'High Pressure',
            'Non-Lube','Portable','Reciprocating. Lub.','Rotary Screw/Sliding Vane','Tank Mounted'],
        "Air Cooling & Heating Equipment" => [],// => ['Air Conditioning Equipment','Blowers','Boilers','Chillers','Cooling Towers','Dryers','Fans','Freezers','Gas Heaters','Heat Exchangers','Heat Treating Units','Humidifiers','Ice Machines','Induction Heaters','Infrared Heaters','Refrigeration Units','Thermal Processing Systems','Water Heaters','xxx','xxx'],
        "Bar Machinery" => [],// => ['Bar Feeds','Bar Loaders','Bar Turners / Peelers'],
        "Bending & Forming Equipment" => [],// => ['Beam Cambering Machines','Beam Coping Machines','Benders, Cleat','Benders, Hand','Benders, Panel','Benders, Pipe, Tube & Bar','Benders, Rebar','Benders, Shape','Bevelers','Brakes, Apron','Brakes, Box & Pan','Brakes, Press','Corner Formers','Crimpers','Elbow Machines','Flaring Machines','Folding Machines','Grooving Machines','Muffler Equipment','Ring Rollers','Rolls, Angle Bending','Rolls, Bending & Curving','Rolls, Billet','Rolls, Cone Bending','Rolls, Corrugating','Rolls, Offset','Rolls, Plate Bending','Straighteners, Flat & Shape','Straighteners, Sheet & Strip','Straighteners, Tube & Bar','Stretch Forming Machines','Swagers','Trimmers','Trimming, Beading & Flanging Machines'],
        "Boring Mills" => [],// => ['Boring Mills, Horizontal, Floor Type','Boring Mills, Horizontal, Planer Type','Boring Mills, Horizontal, Table Type','Jig Borers','Lathes, VTL (Vertical Turret Lathe)'],
        "Broaching Machines & Keyseaters" => [],// => ['Broach Sharpeners','Continuous Chain Broaches','Horizontal Broaches','Horizontal Surface Broaches','Keyseaters','Vertical Hi-Speed Broaches','Vertical Press Type Broaches','Vertical Pull Down Broaches','Vertical Pull Up Broaches','Vertical Surface Broaches (Dual Ram)','Vertical Surface Broaches (Single Ram)','Vertical Table-Up Broaches','Vertical Tri-Way Broaches'],
        "CNC Machinery" => [],// => ['Automatic Screw Machines, Swiss Type','Drilling & Tapping Centers','EDM, Wire','Flame Cutters','Laser Cutters','Lathes, CNC','Lathes, CNC (5-Axis or More)','Machining Centers, Gantry & Double Column','Machining Centers, Horizontal','Machining Centers, Multitasking','Machining Centers, Universal','Machining Centers, Vertical','Machining Centers, Vertical, (5-Axis or More)','Machining Systems, Flexible','Punches, Turret','Waterjet Cutters'],
        "Chemical & Processing Equipment" => [],// => ['Augers','Ball & Pebble Mills','Centrifuges','Chemical & Process Equipment','Dispensing Machines','Evaporators','Filter Presses','Filtration Equipment','Lubrication Equipment','Magnetic Separators','Mixers','Mixers, Gas','Separators','Volumetric Feeders'],
        "Chip, Recycling & Scrap Equipment" => [],
        "Cleaning, Painting & Washing Equipment" => [],
        "Coil Handling Equipment" => [],
        "Construction Equipment" => [],
        "Die Casting Machines" => [],
        "Drilling Machines" => [],
        "EDM Machines" => [],
        "Electrical & Power Equipment" => [],
        "Electronic Equipment" => [],
        "Engine Rebuilding Equipment" => [],
        "Fabrication Equipment" => [],
        "Fastener Equipment" => [],
        "Filtration Systems" => [],
        "Finishing & Lapping Machines" => [],
        "Forging & Foundry Machines" => [],
        "Furnaces & Ovens" => [],
        "Gear Machinery" => [],
        "Grinding Machines" => [],
        "Honing Machines" => [],
        "Inspection & Measuring" => [],
        "Laboratory Equipment" => [],
        "Lasers, Flame, Plasma, Waterjet" => [],
        "Lathes & Turning Machines" => [],
        "Machining Centers" => [],
        "Marking & Etching Machines" => [],
        "Material Handling Items" => [],
        "Milling Machines" => [],
        "Packaging Equipment" => [],
        "Paper & Printing Equipment" => [],
        "Plastics Machinery" => [],
        "Presses (Stamping)" => [],
        "Production Lines & Plants" => [],
        "Pumps, Tanks & Valves" => [],
        "Punching Equipment" => [],
        "Riveters" => [],
        "Robots" => [],
        "Roll Formers & Rolling Mills" => [],
        "Rotary Transfer Machines" => [],
        "Saws" => [],
        "Semiconductor Equipment" => [],
        "Shearing Equipment" => [],
        "Stone & Glass Equipment" => [],
        "Tables" => [],
        "Testing Equipment" => [],
        "Textile Machinery" => [],
        "Tube & Pipe Machinery" => [],
        "Welding Equipment" => [],
        "Wire Machinery" => [],
        "Woodworking Machinery" => [],
    );
}
