shop_product_all_products: 
    path:     /shop/{slug}/all_products/{page}
    defaults:
        _controller: ABOShopBundle:Product:allProducts
        page: 1
    requirements:
        page: \d+

shop_registration_register:
    path:     /register_shop
    defaults:
        _controller: ABOShopBundle:Registration:register

shop_product_prod_by_category:
    path:     shop/{slug}/category/{slug_cat}/{page}
    defaults:
        _controller: ABOShopBundle:Product:prodByCategory
        page: 1
    requirements:
        page: \d+

shop_product_prod_by_collection:
    path:     /shop/{slug}/collection/{slug_col}/{page}
    defaults:
        _controller: ABOShopBundle:Product:prodByCollection
        page: 1
    requirements:
        page: \d+

shop_product_product:
    path:     /shop/{slug}/product/{slug_prod}
    defaults:
        _controller: ABOShopBundle:Product:product

shop_show_home:
    path:     /shop/{slug}
    defaults:
        _controller: ABOShopBundle:Show:home

shop_show_reviews:
    path:     /shop/{slug}/reviews
    defaults:
        _controller: ABOShopBundle:Show:reviews
    methods: [GET, HEAD]

shop_show_reviews_submit:
    path:     /shop/{slug}/reviews/submit
    defaults:
        _controller: ABOShopBundle:Show:submitReviewForm
    methods: [GET, POST]

shop_show_about:
    path:     /shop/{slug}/about
    defaults:
        _controller: ABOShopBundle:Show:about
