<?php

namespace ABO\TrademarkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryTrademarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrangementRepository extends EntityRepository{
    
    /*
     * Trademark:Admin:navigation
     */
    public function getArrangements($trademark, $category) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('ct')
            ->from('ABOTrademarkBundle:Arrangement', 'a')
            ->join('a.category', 'c')
            ->addSelect('c')
            ->where('a.trademark = :tm')
            ->andWhere('a.toProduct = 1')
            ->andWhere($qb->expr()->orX(
                $qb->expr()->eq('a.category', 'NULL'),
                $qb->expr()->eq('a.category', ':category')
            ))
            ->setParameters(array('tm' => $trademark, 'category'=> $category ))
            ->orderBy('a.name', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
